name: Hello World
author: jimmy Misa
description: Test description
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: Ali
outputs:
  time:
    description: "The greeting time"
runs:
  using: "node12"
  main: "dist/index.js"